version: '3.8'

services:
  tg_bot:
    build:
      dockerfile: Docker
    env_file:
      - .env

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
  dtek_checker:
    build:
      context: dtek_checker
      dockerfile: Dockerfile

volumes:
  postgres_data: