
schedule = [
    # Понеділок
    "Понеділок",
    "yes",  # cell-non-scheduled
    "yes",  # cell-non-scheduled
    "no",   # cell-scheduled-maybe
    "no",   # cell-scheduled-maybe
    "no",
    "no",
    "no",
    "no",
    "no",
    "yes",
    "yes",
    "yes",
    "second_half",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "first_half",
    "yes",
    "yes",
    "yes",
    "no",

    # Вівторок
    "Вівторок",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "yes",
    "yes",
    "yes",
    "second_half",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "first_half",
    "yes",
    "yes",
    "yes",
    "no",
    "no",
    "no",
    "no",

    # Середа
    "Середа",
    "no",
    "no",
    "no",
    "yes",
    "yes",
    "yes",
    "second_half",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "first_half",
    "yes",
    "yes",
    "yes",
    "yes",  # 4 consecutive cell-non-scheduled
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",   # (This row actually has 26 TDs after the day name, hence 26 translations)

    # Четвер
    "Четвер",
    "yes",
    "yes",
    "yes",
    "second_half",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "first_half",
    "yes",
    "yes",
    "yes",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "yes",
    "yes",
    "yes",

    # П'ятниця
    "П'ятниця",
    "second_half",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "first_half",
    "yes",
    "yes",
    "yes",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "yes",
    "yes",
    "yes",
    "second_half",
    "no",
    "no",

    # Субота
    "Субота",
    "no",
    "no",
    "no",
    "no",
    "first_half",
    "yes",
    "yes",
    "yes",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "yes",
    "yes",
    "yes",
    "second_half",
    "no",
    "no",
    "no",
    "no",
    "no",

    # Неділя
    "Неділя",
    "no",
    "first_half",
    "yes",
    "yes",
    "yes",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "yes",
    "yes",
    "yes",
    "second_half",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "first_half",
    "yes"
]

zones = ['no', 'maybe', 'maybe', 'maybe', 'yes', 'no', 'no', 'no', 'maybe', 'maybe', 'yes', 'yes', 'yes', 'no', 'no',
         'no', 'maybe', 'maybe', 'maybe', 'yes', 'yes', 'yes', 'no', 'no', 'no', 'no', 'maybe', 'maybe', 'yes', 'yes',
         'yes', 'no', 'no', 'no', 'maybe', 'maybe', 'maybe', 'yes', 'yes', 'yes', 'no', 'no', 'no', 'maybe', 'maybe',
         'maybe', 'yes', 'yes', 'yes', 'no', 'no', 'no', 'maybe', 'maybe', 'maybe', 'yes', 'yes', 'yes', 'no', 'no',
         'no', 'maybe', 'maybe', 'maybe', 'yes', 'yes', 'yes', 'no', 'no', 'no', 'maybe', 'maybe', 'maybe', 'yes',
         'yes', 'yes', 'no', 'no', 'no', 'maybe', 'maybe', 'maybe', 'yes', 'yes', 'yes', 'no', 'no', 'no', 'maybe',
         'maybe', 'maybe', 'yes', 'yes', 'yes', 'no', 'no', 'no', 'maybe', 'maybe', 'maybe', 'yes', 'yes', 'yes', 'no',
         'no', 'no', 'maybe', 'maybe', 'maybe', 'yes', 'yes', 'yes', 'no', 'no', 'no', 'maybe', 'maybe', 'maybe', 'yes',
         'yes', 'yes', 'no', 'no', 'no', 'maybe', 'maybe', 'maybe', 'yes', 'yes', 'yes', 'no', 'no', 'no', 'maybe',
         'maybe', 'maybe', 'yes', 'yes', 'yes', 'no', 'no', 'no', 'maybe', 'maybe', 'maybe', 'yes', 'yes', 'yes', 'no',
         'no', 'no', 'maybe', 'maybe', 'maybe', 'yes', 'yes', 'yes', 'no', 'no', 'no', 'maybe', 'maybe', 'maybe', 'yes',
         'yes', 'yes', 'no', 'no']